// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  become_a_trader: dynamic(() => import("./BecomeATrader")),
  footer_item: dynamic(() => import("./FooterItem")),
  hero: dynamic(() => import("./Hero")),
  highlight: dynamic(() => import("./Highlight")),
  highlighted_articles: dynamic(() => import("./HighlightedArticles")),
  newsletter: dynamic(() => import("./Newsletter")),
  possibilities: dynamic(() => import("./Possibilities")),
  sponsors: dynamic(() => import("./Sponsors")),
  statistics: dynamic(() => import("./Statistics")),
  step_by_step: dynamic(() => import("./StepByStep")),
  testimonial: dynamic(() => import("./Testimonial")),
};
